FROM jenkins/jenkins:lts

USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io

# Give full permission (simple + works)
RUN chmod 666 /var/run/docker.sock || true

USER root
