FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y docker.io wget apt-transport-https gnupg && \
    wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add - && \
    echo "deb https://aquasecurity.github.io/trivy-repo/deb stable main" > /etc/apt/sources.list.d/trivy.list && \
    apt-get update && \
    apt-get install -y trivy

RUN usermod -aG docker jenkins

USER jenkins
